#ifndef CALCULATORLIB_GLOBAL_H
#define CALCULATORLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCULATORLIB_LIBRARY)
#  define CALCULATORLIB_EXPORT Q_DECL_EXPORT
#else
#  define CALCULATORLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCULATORLIB_GLOBAL_H
